# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c6c1cd6d26d07682706d13541d4cec0"
application_url = "https://6d91-71-183-35-90.ngrok-free.app"
embedded = true
name = "gold-price-editor"
handle = "gold-price-editor-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://6d91-71-183-35-90.ngrok-free.app/auth/callback",
  "https://6d91-71-183-35-90.ngrok-free.app/auth/shopify/callback",
  "https://6d91-71-183-35-90.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
